[project]
name = "ogliari"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "automata-lib>=9.1.2",
    "graphviz>=0.21",
    "pandas>=2.3.3",
]
